char* sql =
    "DROP TABLE IF EXISTS PLAYER;"
    "DROP TABLE IF EXISTS TEAM;"
    "CREATE TABLE PLAYER("
    "PLAYER_ID INT PRIMARY KEY     NOT NULL,"
    "TEAM_ID           INT    NOT NULL,"
    "UNIFORM_NUM            INT     NOT NULL,"
    "FIRST_NAME        VARCHAR(10),"
    "LAST_NAME        VARCHAR(10),"
    "MPG        int NOT NULL,"
    "PPG        int NOT NULL,"
    "RPG        int NOT NULL,"
    "APG        int NOT NULL,"
    "SPG        float NOT NULL,"
    "BPG         float NOT NULL );"
    "CREATE TABLE TEAM("
    "TEAM_ID INT PRIMARY KEY     NOT NULL,"
    "NAME           VARCHAR(20)    NOT NULL,"
    "STATE_ID            INT     NOT NULL,"
    "COLOR_ID        INT NOT NULL,"
    "WINS        INT NOT NULL,"
    "LOSSES        INT NOT NULL );"
    "CREATE TABLE TEAM("
    "TEAM_ID INT PRIMARY KEY     NOT NULL,"
    "NAME           VARCHAR(20)    NOT NULL,"
    "STATE_ID            INT     NOT NULL,"
    "COLOR_ID        INT NOT NULL,"
    "WINS        INT NOT NULL,"
    "LOSSES        INT NOT NULL );";